run:
  timeout: 5m
linters:
  enable: [govet, staticcheck, errcheck, revive]

issues:
  # Exclude errcheck in test files - test code often ignores errors intentionally
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      # Logging functions that return errors but are typically ignored
      - (github.com/kardianos/service.Logger).Info
      - (github.com/kardianos/service.Logger).Infof
      - (github.com/kardianos/service.Logger).Warning
      - (github.com/kardianos/service.Logger).Warningf
      - (github.com/kardianos/service.Logger).Error
      - (github.com/kardianos/service.Logger).Errorf
