package wireguard

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestProfileGenerator_GenerateClientConfig(t *testing.T) {
	generator := NewProfileGenerator(
		"vpn.example.com:51820",
		"gOqRLN7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA1bXY=",
		"1.1.1.1, 1.0.0.1",
		1420,
		25,
	)

	t.Run("Success - basic config", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			NetworkName:      "Corporate VPN",
			NetworkCIDR:      "10.0.1.0/24",
			DeviceID:         "dev_456",
			DeviceName:       "Work Laptop",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			PrefixLen:        24,
			UserID:           "user_789",
			UserEmail:        "alice@example.com",
			IncludeHostScope: false,
		}

		config, err := generator.GenerateClientConfig(context.Background(), req)

		require.NoError(t, err)
		assert.Contains(t, config, "[Interface]")
		assert.Contains(t, config, "[Peer]")
		assert.Contains(t, config, "Address = 10.0.1.5/24")
		assert.Contains(t, config, "DNS = 1.1.1.1, 1.0.0.1")
		assert.Contains(t, config, "MTU = 1420")
		assert.Contains(t, config, "PrivateKey = cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=")
		assert.Contains(t, config, "PublicKey = gOqRLN7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA1bXY=")
		assert.Contains(t, config, "Endpoint = vpn.example.com:51820")
		assert.Contains(t, config, "AllowedIPs = 10.0.1.0/24")
		assert.Contains(t, config, "PersistentKeepalive = 25")
		assert.Contains(t, config, "# Generated by GoConnect for Work Laptop")
		assert.Contains(t, config, "# Network: Corporate VPN")
		assert.Contains(t, config, "# User: alice@example.com")
	})

	t.Run("Success - full tunnel mode", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			NetworkName:      "Full Tunnel VPN",
			NetworkCIDR:      "10.0.1.0/24",
			DeviceID:         "dev_456",
			DeviceName:       "Mobile Phone",
			DeviceIP:         "10.0.1.10",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			PrefixLen:        24,
			UserID:           "user_789",
			UserEmail:        "bob@example.com",
			IncludeHostScope: true, // Route all traffic
		}

		config, err := generator.GenerateClientConfig(context.Background(), req)

		require.NoError(t, err)
		assert.Contains(t, config, "AllowedIPs = 0.0.0.0/0, ::/0") // Full tunnel
	})

	t.Run("Validation - missing network_id", func(t *testing.T) {
		req := &ProfileRequest{
			DeviceID:         "dev_456",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			NetworkCIDR:      "10.0.1.0/24",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)

		require.Error(t, err)
		assert.Contains(t, err.Error(), "network_id is required")
	})

	t.Run("Validation - missing device_id", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			NetworkCIDR:      "10.0.1.0/24",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)

		require.Error(t, err)
		assert.Contains(t, err.Error(), "device_id is required")
	})

	t.Run("Validation - invalid CIDR", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceID:         "dev_456",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			NetworkCIDR:      "invalid-cidr",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)

		require.Error(t, err)
		assert.Contains(t, err.Error(), "Invalid network CIDR")
	})

	t.Run("Validation - invalid device IP", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceID:         "dev_456",
			DeviceIP:         "999.999.999.999",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			NetworkCIDR:      "10.0.1.0/24",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)

		require.Error(t, err)
		assert.Contains(t, err.Error(), "Invalid device IP address")
	})

	t.Run("Validation - invalid private key length", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceID:         "dev_456",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "tooshort",
			NetworkCIDR:      "10.0.1.0/24",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)

		require.Error(t, err)
		assert.Contains(t, err.Error(), "Invalid WireGuard private key format")
	})
}

func TestNewProfileGenerator(t *testing.T) {
	t.Run("With defaults", func(t *testing.T) {
		gen := NewProfileGenerator(
			"vpn.example.com:51820",
			"gOqRLN7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA1bXY=",
			"",
			0,
			0,
		)

		assert.Equal(t, "vpn.example.com:51820", gen.serverEndpoint)
		assert.Equal(t, 1420, gen.mtu)
		assert.Equal(t, 25, gen.keepalive)
		assert.Equal(t, "1.1.1.1, 1.0.0.1", gen.dns)
	})

	t.Run("With custom values", func(t *testing.T) {
		gen := NewProfileGenerator(
			"custom.vpn.com:12345",
			"customPubKey",
			"8.8.8.8, 8.8.4.4",
			1280,
			30,
		)

		assert.Equal(t, "custom.vpn.com:12345", gen.serverEndpoint)
		assert.Equal(t, 1280, gen.mtu)
		assert.Equal(t, 30, gen.keepalive)
		assert.Equal(t, "8.8.8.8, 8.8.4.4", gen.dns)
	})
}

func TestProfileRequest_Validate(t *testing.T) {
	generator := NewProfileGenerator(
		"vpn.example.com:51820",
		"gOqRLN7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA1bXY=",
		"1.1.1.1, 1.0.0.1",
		1420,
		25,
	)

	t.Run("Validation - missing device_ip", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceID:         "dev_456",
			DeviceIP:         "",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			NetworkCIDR:      "10.0.1.0/24",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "device_ip is required")
	})

	t.Run("Validation - missing device_private_key", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceID:         "dev_456",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "",
			NetworkCIDR:      "10.0.1.0/24",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "device_private_key is required")
	})

	t.Run("Validation - missing network_cidr", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceID:         "dev_456",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			NetworkCIDR:      "",
			PrefixLen:        24,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "network_cidr is required")
	})

	t.Run("Validation - missing prefix_len", func(t *testing.T) {
		req := &ProfileRequest{
			NetworkID:        "net_123",
			DeviceID:         "dev_456",
			DeviceIP:         "10.0.1.5",
			DevicePrivateKey: "cOvbNjH7xqkK7xKJGVz8M3bKhq8tZ6vS4r9pW3nA2aZ=",
			NetworkCIDR:      "10.0.1.0/24",
			PrefixLen:        0,
		}

		_, err := generator.GenerateClientConfig(context.Background(), req)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "prefix_len is required")
	})
}

