# GoReleaser configuration for GoConnect CLI
# Documentation: https://goreleaser.com

version: 2

project_name: goconnect

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/goconnect
    binary: goconnect
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: cli
    builds:
      - cli
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: orhaniscoding
    name: goconnect
  prerelease: auto
  mode: append
  header: |
    ## 💻 GoConnect CLI {{ .Tag }}
    
    Terminal application with TUI for GoConnect networks.
  footer: |
    ---
    
    ### Quick Start
    
    ```bash
    # Download and extract
    tar -xzf goconnect_{{ .Version }}_linux_amd64.tar.gz
    
    # Run setup wizard
    ./goconnect setup
    
    # Or launch TUI
    ./goconnect
    ```
