# yaml-language-server: $schema=
# NOTE: Editor might warn about missing 'version', but golangci-lint does not accept `version` key in config.
run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - gocritic

issues:
  exclude-rules:
    # Exclude errcheck in test files - test assertions handle errors
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - ineffassign
    
    # Exclude errcheck for deferred rollback calls - common pattern
    - text: "Error return value of `.*\\.Rollback\\(\\)` is not checked"
      linters:
        - errcheck

    # Exclude errcheck for json.Unmarshal/Encode - often intentional
    - text: "Error return value of `json\\."
      linters:
        - errcheck
    - text: "Error return value of `\\(\\*encoding/json"
      linters:
        - errcheck

    # Exclude errcheck for websocket operations - fire and forget pattern
    - path: internal/websocket/
      linters:
        - errcheck

    # Exclude errcheck for connection deadline and write operations
    - text: "Error return value of `.*\\.(SetReadDeadline|SetWriteDeadline|WriteMessage|Write)\\("
      linters:
        - errcheck
    
    # Exclude errcheck for Send calls - fire and forget pattern
    - text: "Error return value of `.*\\.Send\\("
      linters:
        - errcheck

    # Exclude unused functions in test helpers
    - path: test_helpers\.go
      linters:
        - unused
    
    # Exclude errcheck for device repo update in background goroutine
    - path: internal/service/device\.go
      text: "Error return value of `s.deviceRepo.Update`"
      linters:
        - errcheck
    
    # Exclude gocritic exitAfterDefer - intentional fatal on startup failure
    - text: "exitAfterDefer"
      linters:
        - gocritic
    
    # Exclude gocritic ifElseChain - stylistic choice
    - text: "ifElseChain"
      linters:
        - gocritic
    
    # Exclude gocritic elseif - stylistic choice
    - text: "elseif"
      linters:
        - gocritic

    # Exclude w.Write errors in HTTP handlers - middleware pattern
    - path: internal/handler/
      text: "Error return value of `w.Write`"
      linters:
        - errcheck

linters-settings:
  errcheck:
    # Check for ignored errors with blank identifier
    check-blank: false
    # Don't report expected errors in certain situations
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.Unmarshal
      - (*database/sql.Tx).Rollback
      - (*net.Conn).SetReadDeadline
      - (*net.Conn).SetWriteDeadline
  
  gocritic:
    disabled-checks:
      - exitAfterDefer
      - ifElseChain
      - elseif